const translations={
  en:{
    metaTitle:'AETERNUM — UX Case Study',
    metaDescription:'UX case study for AETERNUM, a luxury jewelry concept experienced as a journey through a digital Pantheon.',
    'nav.live':'View Live Project',
    'hero.label':'UX CASE STUDY','hero.title':'Designing a Digital Pantheon for Luxury Jewelry','hero.lede':'A luxury jewelry concept where the website is experienced as a journey through a digital Pantheon instead of a traditional online store.',
    'meta.role.label':'Role','meta.role.value':'UX/UI Designer','meta.type.label':'Project Type','meta.type.value':'Luxury Jewelry Concept','meta.focus.label':'Focus','meta.focus.value':'Spatial Navigation · Storytelling · Immersive UX · Luxury Art Direction',
    'overview.title':'Project Overview','overview.p1':'Traditional luxury jewelry websites usually present products through grids and product cards.','overview.p2':'AETERNUM explores a different idea.','overview.p3':'Instead of browsing products, visitors enter a marble Pantheon where every jewelry collection occupies its own architectural space inspired by a Greek or Roman deity.','overview.p4':'Navigation becomes part of the experience. Users do not simply move between pages; they walk through the building, discovering collections as destinations rather than categories.','overview.p5':'The goal was to combine storytelling, architecture, and interaction design into a calm luxury experience that encourages exploration instead of fast shopping.',
    'problem.title':'UX Problem','problem.p1':'Most e-commerce websites encourage users to scan products as quickly as possible.','problem.p2':'For a fictional luxury jewelry house, this approach weakens the emotional value of the pieces.','problem.p3':'The challenge was to create an interface where jewelry feels like museum artifacts instead of inventory while keeping navigation intuitive and easy to understand.',
    'goals.title':'UX Goals','goals.1':'Replace traditional navigation with architectural exploration.','goals.2':'Give every collection its own visual identity.','goals.3':'Keep jewelry as the visual focus.','goals.4':'Slow down browsing to encourage appreciation.','goals.5':'Maintain a clean and minimal luxury interface.','goals.6':'Create memorable navigation without sacrificing usability.',
    'journey.title':'User Journey','journey.1':'Entrance','journey.2':'Central Hall','journey.3':'Choose Collection','journey.4':'Enter Hall','journey.5':'Inspect Jewelry','journey.6':'Open Product Detail','journey.7':'Request Private Viewing','journey.note':'The journey mirrors the experience of walking through a museum rather than browsing an online catalog.',
    'navigation.title':'Navigation Concept','navigation.p1':'The Pantheon itself becomes the navigation system.','navigation.p2':'Instead of selecting categories from a menu, users move through architectural space.','navigation.p3':'Each archway represents a different collection inspired by a classical deity.','navigation.p4':'This creates stronger orientation, emotional engagement, and a clearer connection between the collection theme and its visual environment.','navigation.p5':'Traditional navigation remains available only as secondary support.',
    'identity.title':'Collection Identity','identity.intro':'Each hall communicates its own atmosphere through architecture, lighting, materials, and color.','identity.zeus':'Power · Warm golden light · Sharp geometry · Yellow gemstones','identity.poseidon':'Calm · Cool reflections · Aquamarines · Fluid forms','identity.aphrodite':'Softness · Pearl tones · Rose gold · Organic shapes','identity.hades':'Authority · Dark stone · Onyx · Focused lighting','identity.artemis':'Silence · Moonlight · Silver · Natural shadows','identity.athena':'Precision · Balanced symmetry · Emerald accents · Architectural forms','identity.apollo':'Energy · Warm sunlight · Gold · Radiating geometry','identity.note':'Every collection is immediately recognizable without relying on large amounts of text.',
    'product.title':'Product Experience','product.p1':'Products are displayed as artifacts placed on marble pedestals.','product.p2':'The surrounding architecture supports the story but never competes with the jewelry.','product.p3':'Clicking a pedestal smoothly focuses the camera on the selected piece before opening its information panel.','product.p4':'Instead of using a traditional “Add to Cart” action, the interface offers “Request Private Viewing,” reinforcing the positioning of the fictional luxury house.',
    'interaction.title':'Interaction Design','interaction.p1':'Every interaction is designed to feel slow, calm, and intentional.','interaction.label':'Key interactions include:','interaction.1':'Camera movement between halls.','interaction.2':'Soft parallax through architectural layers.','interaction.3':'Rotating hero jewelry.','interaction.4':'Pedestal hover highlighting.','interaction.5':'Smooth product focus transitions.','interaction.6':'Gentle lighting changes between collections.','interaction.p2':'Animations are used to guide attention rather than impress through speed.',
    'hierarchy.title':'Information Hierarchy','hierarchy.1':'Pantheon','hierarchy.2':'Collection Hall','hierarchy.3':'Hero Jewelry','hierarchy.4':'Supporting Pieces','hierarchy.5':'Product Detail','hierarchy.6':'Private Viewing','hierarchy.note':'Information appears progressively, reducing cognitive load while encouraging exploration.',
    'visual.title':'Visual UX Reasoning','visual.p1':'Architecture is used as an interface rather than decoration.','visual.p2':'White marble creates neutrality and allows the jewelry to become the visual focus.','visual.p3':'Each collection introduces its own lighting, color accents, and atmosphere while maintaining a consistent visual language across the experience.','visual.p4':'The restrained palette supports a premium identity without relying on excessive ornament or bright luxury clichés.',
    'accessibility.title':'Accessibility','accessibility.p1':'Although highly visual, the experience follows fundamental usability principles.','accessibility.1':'Keyboard navigation.','accessibility.2':'Visible focus states.','accessibility.3':'High text contrast.','accessibility.4':'Reduced motion option.','accessibility.5':'Consistent interaction patterns.','accessibility.6':'Clear navigation back to the Central Hall.','accessibility.p2':'Atmosphere should enhance usability, never replace it.',
    'decisions.title':'Key Design Decisions','decisions.1':'Architecture replaces traditional navigation.','decisions.2':'Collections become physical destinations instead of menu categories.','decisions.3':'Jewelry always remains the visual hero.','decisions.4':'Slow transitions reinforce luxury.','decisions.5':'Museum presentation replaces product catalog presentation.','decisions.6':'Private Viewing replaces Add to Cart to strengthen exclusivity.',
    'reflection.title':'Reflection','reflection.p1':'AETERNUM explores how architecture can become part of user experience rather than simple decoration.','reflection.p2':'The project transforms navigation into spatial storytelling while preserving usability through clear interaction patterns and progressive information.','reflection.p3':'Instead of encouraging rapid consumption, the interface invites visitors to slow down, observe details, and experience each collection as a curated exhibition.','reflection.p4':'The result is a luxury concept that combines digital interaction, architectural inspiration, and storytelling into a single immersive experience.',
    'footer.note':'UX Case Study · Digital Pantheon'
  },
  ru:{
    metaTitle:'AETERNUM — UX-кейс',
    metaDescription:'UX-кейс AETERNUM: концепт luxury jewelry, где сайт ощущается как путешествие по цифровому Пантеону.',
    'nav.live':'Открыть проект',
    'hero.label':'UX-КЕЙС','hero.title':'Проектирование цифрового Пантеона для ювелирного бренда','hero.lede':'Концепт luxury jewelry, где сайт воспринимается как путешествие по цифровому Пантеону, а не как обычный интернет-магазин.',
    'meta.role.label':'Роль','meta.role.value':'UX/UI дизайнер','meta.type.label':'Тип проекта','meta.type.value':'Концепт luxury jewelry','meta.focus.label':'Фокус','meta.focus.value':'Пространственная навигация · Сторителлинг · Иммерсивный UX · Luxury art direction',
    'overview.title':'Обзор проекта','overview.p1':'Традиционные сайты luxury jewelry чаще всего показывают изделия через сетки и карточки товаров.','overview.p2':'AETERNUM исследует другую идею.','overview.p3':'Вместо просмотра товаров посетитель входит в мраморный Пантеон, где каждая ювелирная коллекция занимает собственное архитектурное пространство, вдохновлённое греческим или римским божеством.','overview.p4':'Навигация становится частью опыта. Пользователь не просто переходит между страницами — он движется по зданию и открывает коллекции как направления, а не как категории.','overview.p5':'Целью было объединить сторителлинг, архитектуру и интерактивный дизайн в спокойный luxury-опыт, который поощряет исследование вместо быстрого шопинга.',
    'problem.title':'UX-проблема','problem.p1':'Большинство e-commerce сайтов побуждают пользователя как можно быстрее просматривать товары.','problem.p2':'Для вымышленного luxury jewelry house такой подход ослабляет эмоциональную ценность украшений.','problem.p3':'Задача состояла в том, чтобы создать интерфейс, где украшения ощущаются музейными артефактами, а не складским ассортиментом, сохраняя при этом понятную и интуитивную навигацию.',
    'goals.title':'UX-цели','goals.1':'Заменить традиционную навигацию архитектурным исследованием пространства.','goals.2':'Дать каждой коллекции собственную визуальную идентичность.','goals.3':'Оставить украшения главным визуальным фокусом.','goals.4':'Замедлить просмотр, чтобы усилить внимательное восприятие.','goals.5':'Сохранить чистый и минималистичный luxury-интерфейс.','goals.6':'Создать запоминающуюся навигацию без потери удобства.',
    'journey.title':'Пользовательский путь','journey.1':'Вход','journey.2':'Центральный зал','journey.3':'Выбор коллекции','journey.4':'Вход в зал','journey.5':'Осмотр украшений','journey.6':'Открытие карточки изделия','journey.7':'Запрос приватного просмотра','journey.note':'Этот путь повторяет опыт прогулки по музею, а не просмотра онлайн-каталога.',
    'navigation.title':'Концепция навигации','navigation.p1':'Сам Пантеон становится навигационной системой.','navigation.p2':'Вместо выбора категорий из меню пользователь перемещается внутри архитектурного пространства.','navigation.p3':'Каждая арка представляет отдельную коллекцию, вдохновлённую классическим божеством.','navigation.p4':'Так усиливается ориентация, эмоциональное вовлечение и связь между темой коллекции и её визуальной средой.','navigation.p5':'Традиционная навигация остаётся только как вспомогательный слой.',
    'identity.title':'Идентичность коллекций','identity.intro':'Каждый зал передаёт собственную атмосферу через архитектуру, свет, материалы и цвет.','identity.zeus':'Сила · Тёплый золотой свет · Острая геометрия · Жёлтые камни','identity.poseidon':'Спокойствие · Холодные отражения · Аквамарины · Текучие формы','identity.aphrodite':'Нежность · Жемчужные тона · Розовое золото · Органические формы','identity.hades':'Власть · Тёмный камень · Оникс · Направленный свет','identity.artemis':'Тишина · Лунный свет · Серебро · Природные тени','identity.athena':'Точность · Уравновешенная симметрия · Изумрудные акценты · Архитектурные формы','identity.apollo':'Энергия · Тёплый солнечный свет · Золото · Лучевая геометрия','identity.note':'Каждая коллекция считывается сразу, без необходимости в больших текстовых объяснениях.',
    'product.title':'Опыт взаимодействия с изделием','product.p1':'Украшения представлены как артефакты на мраморных пьедесталах.','product.p2':'Окружающая архитектура поддерживает историю, но не конкурирует с украшениями.','product.p3':'Клик по пьедесталу плавно фокусирует камеру на выбранном изделии перед открытием информационной панели.','product.p4':'Вместо привычного действия “Add to Cart” интерфейс предлагает “Request Private Viewing”, усиливая образ закрытого luxury house.',
    'interaction.title':'Дизайн взаимодействий','interaction.p1':'Каждое взаимодействие должно ощущаться медленным, спокойным и намеренным.','interaction.label':'Ключевые взаимодействия включают:','interaction.1':'Движение камеры между залами.','interaction.2':'Мягкий параллакс архитектурных слоёв.','interaction.3':'Вращение главного украшения.','interaction.4':'Подсветку пьедестала при наведении.','interaction.5':'Плавные переходы фокуса к изделию.','interaction.6':'Деликатные изменения света между коллекциями.','interaction.p2':'Анимации направляют внимание, а не пытаются впечатлить скоростью.',
    'hierarchy.title':'Информационная иерархия','hierarchy.1':'Пантеон','hierarchy.2':'Зал коллекции','hierarchy.3':'Главное украшение','hierarchy.4':'Дополнительные изделия','hierarchy.5':'Детали изделия','hierarchy.6':'Приватный просмотр','hierarchy.note':'Информация появляется постепенно, снижая когнитивную нагрузку и поддерживая исследование.',
    'visual.title':'Визуальная UX-логика','visual.p1':'Архитектура используется как интерфейс, а не как декорация.','visual.p2':'Белый мрамор создаёт нейтральность и позволяет украшениям стать главным визуальным фокусом.','visual.p3':'Каждая коллекция добавляет собственный свет, цветовые акценты и атмосферу, сохраняя единый визуальный язык всего опыта.','visual.p4':'Сдержанная палитра поддерживает премиальную идентичность без лишнего орнамента и ярких luxury-клише.',
    'accessibility.title':'Доступность','accessibility.p1':'Несмотря на высокую визуальность, опыт следует базовым принципам удобства.','accessibility.1':'Навигация с клавиатуры.','accessibility.2':'Видимые focus-состояния.','accessibility.3':'Высокий контраст текста.','accessibility.4':'Опция reduced motion.','accessibility.5':'Последовательные паттерны взаимодействия.','accessibility.6':'Понятный возврат в Центральный зал.','accessibility.p2':'Атмосфера должна усиливать удобство, а не заменять его.',
    'decisions.title':'Ключевые дизайн-решения','decisions.1':'Архитектура заменяет традиционную навигацию.','decisions.2':'Коллекции становятся физическими направлениями, а не пунктами меню.','decisions.3':'Украшения всегда остаются главным визуальным героем.','decisions.4':'Медленные переходы усиливают ощущение luxury.','decisions.5':'Музейная подача заменяет товарный каталог.','decisions.6':'Private Viewing заменяет Add to Cart и усиливает эксклюзивность.',
    'reflection.title':'Рефлексия','reflection.p1':'AETERNUM исследует, как архитектура может стать частью пользовательского опыта, а не просто декоративным фоном.','reflection.p2':'Проект превращает навигацию в пространственный сторителлинг, сохраняя удобство через ясные паттерны взаимодействия и постепенную подачу информации.','reflection.p3':'Вместо быстрого потребления интерфейс приглашает посетителя замедлиться, рассмотреть детали и пережить каждую коллекцию как кураторскую выставку.','reflection.p4':'Результат — luxury-концепт, который объединяет цифровое взаимодействие, архитектурное вдохновение и сторителлинг в единый иммерсивный опыт.',
    'footer.note':'UX-кейс · Цифровой Пантеон'
  },
  pl:{
    metaTitle:'AETERNUM — Studium UX',
    metaDescription:'Studium UX projektu AETERNUM: koncepcja luxury jewelry, w której strona jest podróżą przez cyfrowy Panteon.',
    'nav.live':'Zobacz projekt',
    'hero.label':'STUDIUM UX','hero.title':'Projektowanie cyfrowego Panteonu dla marki biżuterii luksusowej','hero.lede':'Koncepcja luxury jewelry, w której strona jest doświadczana jako podróż przez cyfrowy Panteon, a nie jako tradycyjny sklep online.',
    'meta.role.label':'Rola','meta.role.value':'Projektantka UX/UI','meta.type.label':'Typ projektu','meta.type.value':'Koncepcja luxury jewelry','meta.focus.label':'Fokus','meta.focus.value':'Nawigacja przestrzenna · Storytelling · Immersyjny UX · Luxury art direction',
    'overview.title':'Przegląd projektu','overview.p1':'Tradycyjne strony luksusowej biżuterii zwykle prezentują produkty przez siatki i karty produktowe.','overview.p2':'AETERNUM sprawdza inną ideę.','overview.p3':'Zamiast przeglądać produkty, odwiedzający wchodzą do marmurowego Panteonu, w którym każda kolekcja zajmuje własną przestrzeń architektoniczną inspirowaną greckim lub rzymskim bóstwem.','overview.p4':'Nawigacja staje się częścią doświadczenia. Użytkownicy nie tylko przechodzą między stronami — poruszają się po budynku i odkrywają kolekcje jako miejsca docelowe, nie kategorie.','overview.p5':'Celem było połączenie storytellingu, architektury i projektowania interakcji w spokojne luksusowe doświadczenie, które zachęca do eksploracji zamiast szybkich zakupów.',
    'problem.title':'Problem UX','problem.p1':'Większość stron e-commerce zachęca użytkowników do jak najszybszego skanowania produktów.','problem.p2':'Dla fikcyjnego domu luksusowej biżuterii takie podejście osłabia emocjonalną wartość przedmiotów.','problem.p3':'Wyzwanie polegało na stworzeniu interfejsu, w którym biżuteria przypomina muzealne artefakty, a nie magazynowy asortyment, przy zachowaniu intuicyjnej i łatwej nawigacji.',
    'goals.title':'Cele UX','goals.1':'Zastąpić tradycyjną nawigację eksploracją architektury.','goals.2':'Nadać każdej kolekcji własną tożsamość wizualną.','goals.3':'Utrzymać biżuterię jako główny punkt uwagi.','goals.4':'Spowolnić przeglądanie, aby zachęcić do uważnej obserwacji.','goals.5':'Zachować czysty, minimalistyczny interfejs luksusowy.','goals.6':'Stworzyć zapamiętywalną nawigację bez utraty użyteczności.',
    'journey.title':'Ścieżka użytkownika','journey.1':'Wejście','journey.2':'Sala centralna','journey.3':'Wybór kolekcji','journey.4':'Wejście do sali','journey.5':'Oglądanie biżuterii','journey.6':'Otwarcie szczegółów produktu','journey.7':'Prośba o prywatną prezentację','journey.note':'Ta ścieżka przypomina spacer po muzeum bardziej niż przeglądanie katalogu online.',
    'navigation.title':'Koncepcja nawigacji','navigation.p1':'Sam Panteon staje się systemem nawigacji.','navigation.p2':'Zamiast wybierać kategorie z menu, użytkownicy poruszają się w przestrzeni architektonicznej.','navigation.p3':'Każdy łuk reprezentuje inną kolekcję inspirowaną klasycznym bóstwem.','navigation.p4':'Buduje to silniejszą orientację, emocjonalne zaangażowanie i wyraźniejsze połączenie motywu kolekcji z jej środowiskiem wizualnym.','navigation.p5':'Tradycyjna nawigacja pozostaje wyłącznie wsparciem drugiego planu.',
    'identity.title':'Tożsamość kolekcji','identity.intro':'Każda sala komunikuje własną atmosferę przez architekturę, światło, materiały i kolor.','identity.zeus':'Moc · Ciepłe złote światło · Ostra geometria · Żółte kamienie','identity.poseidon':'Spokój · Chłodne refleksy · Akwamaryny · Płynne formy','identity.aphrodite':'Miękkość · Perłowe tony · Różowe złoto · Organiczne kształty','identity.hades':'Autorytet · Ciemny kamień · Onyks · Skupione światło','identity.artemis':'Cisza · Światło księżyca · Srebro · Naturalne cienie','identity.athena':'Precyzja · Zrównoważona symetria · Szmaragdowe akcenty · Formy architektoniczne','identity.apollo':'Energia · Ciepłe słońce · Złoto · Promienista geometria','identity.note':'Każda kolekcja jest rozpoznawalna od razu, bez potrzeby dużej ilości tekstu.',
    'product.title':'Doświadczenie produktu','product.p1':'Produkty są prezentowane jak artefakty ustawione na marmurowych piedestałach.','product.p2':'Otaczająca architektura wspiera historię, ale nigdy nie konkuruje z biżuterią.','product.p3':'Kliknięcie piedestału płynnie skupia kamerę na wybranym elemencie przed otwarciem panelu informacyjnego.','product.p4':'Zamiast tradycyjnego działania „Add to Cart” interfejs oferuje „Request Private Viewing”, wzmacniając pozycjonowanie fikcyjnego domu luksusowego.',
    'interaction.title':'Projektowanie interakcji','interaction.p1':'Każda interakcja ma być powolna, spokojna i świadoma.','interaction.label':'Kluczowe interakcje obejmują:','interaction.1':'Ruch kamery między salami.','interaction.2':'Delikatny paralaks warstw architektonicznych.','interaction.3':'Obracającą się biżuterię hero.','interaction.4':'Podświetlenie piedestału po najechaniu.','interaction.5':'Płynne przejścia fokusu na produkt.','interaction.6':'Subtelne zmiany światła między kolekcjami.','interaction.p2':'Animacje prowadzą uwagę, zamiast imponować szybkością.',
    'hierarchy.title':'Hierarchia informacji','hierarchy.1':'Panteon','hierarchy.2':'Sala kolekcji','hierarchy.3':'Biżuteria hero','hierarchy.4':'Elementy wspierające','hierarchy.5':'Szczegóły produktu','hierarchy.6':'Prywatna prezentacja','hierarchy.note':'Informacja pojawia się stopniowo, zmniejszając obciążenie poznawcze i zachęcając do eksploracji.',
    'visual.title':'Uzasadnienie wizualnego UX','visual.p1':'Architektura jest używana jako interfejs, nie jako dekoracja.','visual.p2':'Biały marmur tworzy neutralność i pozwala biżuterii stać się głównym punktem wizualnym.','visual.p3':'Każda kolekcja wprowadza własne światło, akcenty kolorystyczne i atmosferę, zachowując spójny język wizualny całego doświadczenia.','visual.p4':'Powściągliwa paleta wspiera premium identity bez nadmiaru ornamentu i jaskrawych luksusowych klisz.',
    'accessibility.title':'Dostępność','accessibility.p1':'Choć doświadczenie jest mocno wizualne, opiera się na podstawowych zasadach użyteczności.','accessibility.1':'Nawigacja klawiaturą.','accessibility.2':'Widoczne stany focus.','accessibility.3':'Wysoki kontrast tekstu.','accessibility.4':'Opcja ograniczenia ruchu.','accessibility.5':'Spójne wzorce interakcji.','accessibility.6':'Czytelny powrót do Sali Centralnej.','accessibility.p2':'Atmosfera powinna wzmacniać użyteczność, nigdy jej nie zastępować.',
    'decisions.title':'Kluczowe decyzje projektowe','decisions.1':'Architektura zastępuje tradycyjną nawigację.','decisions.2':'Kolekcje stają się fizycznymi miejscami docelowymi zamiast kategoriami menu.','decisions.3':'Biżuteria zawsze pozostaje wizualnym bohaterem.','decisions.4':'Powolne przejścia wzmacniają poczucie luksusu.','decisions.5':'Prezentacja muzealna zastępuje katalog produktowy.','decisions.6':'Private Viewing zastępuje Add to Cart, wzmacniając ekskluzywność.',
    'reflection.title':'Refleksja','reflection.p1':'AETERNUM pokazuje, jak architektura może stać się częścią doświadczenia użytkownika, a nie tylko dekoracją.','reflection.p2':'Projekt przekształca nawigację w przestrzenny storytelling, zachowując użyteczność dzięki jasnym wzorcom interakcji i stopniowemu ujawnianiu informacji.','reflection.p3':'Zamiast zachęcać do szybkiej konsumpcji, interfejs zaprasza odwiedzających do zwolnienia, obserwacji detali i doświadczenia każdej kolekcji jak kuratorskiej wystawy.','reflection.p4':'Rezultatem jest koncepcja luxury, która łączy cyfrową interakcję, inspirację architekturą i storytelling w jedno immersyjne doświadczenie.',
    'footer.note':'Studium UX · Cyfrowy Panteon'
  },
  uk:{
    metaTitle:'AETERNUM — UX-кейс',
    metaDescription:'UX-кейс AETERNUM: концепт luxury jewelry, у якому сайт переживається як подорож цифровим Пантеоном.',
    'nav.live':'Відкрити проєкт',
    'hero.label':'UX-КЕЙС','hero.title':'Проєктування цифрового Пантеону для ювелірного бренду','hero.lede':'Концепт luxury jewelry, у якому сайт сприймається як подорож цифровим Пантеоном, а не як традиційний інтернет-магазин.',
    'meta.role.label':'Роль','meta.role.value':'UX/UI дизайнерка','meta.type.label':'Тип проєкту','meta.type.value':'Концепт luxury jewelry','meta.focus.label':'Фокус','meta.focus.value':'Просторова навігація · Сторітелінг · Імерсивний UX · Luxury art direction',
    'overview.title':'Огляд проєкту','overview.p1':'Традиційні сайти luxury jewelry зазвичай показують вироби через сітки та продуктові картки.','overview.p2':'AETERNUM досліджує іншу ідею.','overview.p3':'Замість перегляду товарів відвідувачі входять до мармурового Пантеону, де кожна ювелірна колекція займає власний архітектурний простір, натхнений грецьким або римським божеством.','overview.p4':'Навігація стає частиною досвіду. Користувачі не просто переходять між сторінками — вони рухаються будівлею й відкривають колекції як напрямки, а не як категорії.','overview.p5':'Мета полягала в тому, щоб об’єднати сторітелінг, архітектуру та дизайн взаємодії у спокійний luxury-досвід, який заохочує дослідження замість швидкого шопінгу.',
    'problem.title':'UX-проблема','problem.p1':'Більшість e-commerce сайтів заохочують користувачів якнайшвидше сканувати товари.','problem.p2':'Для вигаданого luxury jewelry house такий підхід послаблює емоційну цінність виробів.','problem.p3':'Виклик полягав у створенні інтерфейсу, де прикраси відчуваються музейними артефактами, а не складським асортиментом, і водночас навігація залишається інтуїтивною та зрозумілою.',
    'goals.title':'UX-цілі','goals.1':'Замінити традиційну навігацію архітектурним дослідженням простору.','goals.2':'Надати кожній колекції власну візуальну ідентичність.','goals.3':'Зберегти прикраси головним візуальним фокусом.','goals.4':'Сповільнити перегляд, щоб заохотити уважне сприйняття.','goals.5':'Підтримати чистий і мінімалістичний luxury-інтерфейс.','goals.6':'Створити пам’ятну навігацію без втрати зручності.',
    'journey.title':'Шлях користувача','journey.1':'Вхід','journey.2':'Центральна зала','journey.3':'Вибір колекції','journey.4':'Вхід до зали','journey.5':'Огляд прикрас','journey.6':'Відкриття деталей виробу','journey.7':'Запит приватного перегляду','journey.note':'Цей шлях повторює досвід прогулянки музеєм, а не перегляду онлайн-каталогу.',
    'navigation.title':'Концепція навігації','navigation.p1':'Сам Пантеон стає навігаційною системою.','navigation.p2':'Замість вибору категорій із меню користувачі переміщуються всередині архітектурного простору.','navigation.p3':'Кожна арка представляє окрему колекцію, натхненну класичним божеством.','navigation.p4':'Це посилює орієнтацію, емоційне залучення та зв’язок між темою колекції і її візуальним середовищем.','navigation.p5':'Традиційна навігація залишається лише як допоміжний шар.',
    'identity.title':'Ідентичність колекцій','identity.intro':'Кожна зала передає власну атмосферу через архітектуру, світло, матеріали й колір.','identity.zeus':'Сила · Тепле золоте світло · Гостра геометрія · Жовте каміння','identity.poseidon':'Спокій · Холодні відбиття · Аквамарини · Плинні форми','identity.aphrodite':'М’якість · Перлинні тони · Рожеве золото · Органічні форми','identity.hades':'Авторитет · Темний камінь · Онікс · Спрямоване світло','identity.artemis':'Тиша · Місячне світло · Срібло · Природні тіні','identity.athena':'Точність · Збалансована симетрія · Смарагдові акценти · Архітектурні форми','identity.apollo':'Енергія · Тепле сонячне світло · Золото · Променева геометрія','identity.note':'Кожна колекція впізнається одразу, без потреби у великих текстових поясненнях.',
    'product.title':'Досвід взаємодії з виробом','product.p1':'Прикраси представлені як артефакти на мармурових п’єдесталах.','product.p2':'Навколишня архітектура підтримує історію, але ніколи не конкурує з прикрасами.','product.p3':'Клік по п’єдесталу плавно фокусує камеру на вибраному виробі перед відкриттям інформаційної панелі.','product.p4':'Замість традиційної дії “Add to Cart” інтерфейс пропонує “Request Private Viewing”, підсилюючи позиціонування вигаданого luxury house.',
    'interaction.title':'Дизайн взаємодій','interaction.p1':'Кожна взаємодія має відчуватися повільною, спокійною та усвідомленою.','interaction.label':'Ключові взаємодії включають:','interaction.1':'Рух камери між залами.','interaction.2':'М’який паралакс архітектурних шарів.','interaction.3':'Обертання головної прикраси.','interaction.4':'Підсвічування п’єдесталу при наведенні.','interaction.5':'Плавні переходи фокусу до виробу.','interaction.6':'Делікатні зміни світла між колекціями.','interaction.p2':'Анімації спрямовують увагу, а не намагаються вразити швидкістю.',
    'hierarchy.title':'Інформаційна ієрархія','hierarchy.1':'Пантеон','hierarchy.2':'Зала колекції','hierarchy.3':'Головна прикраса','hierarchy.4':'Додаткові вироби','hierarchy.5':'Деталі виробу','hierarchy.6':'Приватний перегляд','hierarchy.note':'Інформація з’являється поступово, зменшуючи когнітивне навантаження й підтримуючи дослідження.',
    'visual.title':'Візуальна UX-логіка','visual.p1':'Архітектура використовується як інтерфейс, а не як декорація.','visual.p2':'Білий мармур створює нейтральність і дозволяє прикрасам стати головним візуальним фокусом.','visual.p3':'Кожна колекція додає власне світло, колірні акценти й атмосферу, зберігаючи єдину візуальну мову всього досвіду.','visual.p4':'Стримана палітра підтримує premium identity без надмірного орнаменту та яскравих luxury-кліше.',
    'accessibility.title':'Доступність','accessibility.p1':'Попри високу візуальність, досвід дотримується базових принципів зручності.','accessibility.1':'Навігація з клавіатури.','accessibility.2':'Видимі focus-стани.','accessibility.3':'Високий контраст тексту.','accessibility.4':'Опція reduced motion.','accessibility.5':'Послідовні патерни взаємодії.','accessibility.6':'Зрозуміле повернення до Центральної зали.','accessibility.p2':'Атмосфера має підсилювати зручність, а не замінювати її.',
    'decisions.title':'Ключові дизайн-рішення','decisions.1':'Архітектура замінює традиційну навігацію.','decisions.2':'Колекції стають фізичними напрямками замість категорій меню.','decisions.3':'Прикраси завжди залишаються головним візуальним героєм.','decisions.4':'Повільні переходи підсилюють відчуття luxury.','decisions.5':'Музейна подача замінює продуктовий каталог.','decisions.6':'Private Viewing замінює Add to Cart і підсилює ексклюзивність.',
    'reflection.title':'Рефлексія','reflection.p1':'AETERNUM досліджує, як архітектура може стати частиною користувацького досвіду, а не просто декоративним фоном.','reflection.p2':'Проєкт перетворює навігацію на просторовий сторітелінг, зберігаючи зручність через зрозумілі патерни взаємодії та поступову подачу інформації.','reflection.p3':'Замість швидкого споживання інтерфейс запрошує відвідувача сповільнитися, роздивитися деталі й пережити кожну колекцію як кураторську виставку.','reflection.p4':'Результат — luxury-концепт, що поєднує цифрову взаємодію, архітектурне натхнення й сторітелінг в єдиний імерсивний досвід.',
    'footer.note':'UX-кейс · Цифровий Пантеон'
  }
};

const supported=['ru','pl','uk','en'];
const stored=localStorage.getItem('aeternum-case-lang');
const browser=(navigator.language||'en').slice(0,2).toLowerCase();
const initial=supported.includes(stored)?stored:(supported.includes(browser)?browser:'en');

function setLanguage(lang){
  const dict=translations[lang]||translations.en;
  document.documentElement.lang=lang;
  document.title=dict.metaTitle;
  const meta=document.querySelector('meta[name="description"]');
  if(meta)meta.setAttribute('content',dict.metaDescription);
  document.querySelectorAll('[data-i18n]').forEach(node=>{
    const value=dict[node.dataset.i18n];
    if(value)node.textContent=value;
  });
  document.querySelectorAll('[data-lang]').forEach(button=>{
    const active=button.dataset.lang===lang;
    button.setAttribute('aria-pressed',String(active));
  });
  localStorage.setItem('aeternum-case-lang',lang);
}

document.querySelectorAll('[data-lang]').forEach(button=>{
  button.addEventListener('click',()=>setLanguage(button.dataset.lang));
});

document.addEventListener('pointermove',event=>{
  document.documentElement.style.setProperty('--mx',`${event.clientX}px`);
  document.documentElement.style.setProperty('--my',`${event.clientY}px`);
});

setLanguage(initial);
