const i18nNodes = [...document.querySelectorAll("[data-i18n]")];
const languageButtons = [...document.querySelectorAll("[data-lang]")];
const titleNode = document.querySelector("title");
const descriptionNode = document.querySelector('meta[name="description"]');
const prefersReducedMotion = matchMedia("(prefers-reduced-motion: reduce)");

i18nNodes.forEach(node => {
  node.dataset.i18nDefault = node.innerHTML;
});

const languageMeta = {
  en: {
    html: "en",
    title: "UX Case Study - Case File #371 - The Blackwood Earrings",
    description: "UX case study for Case File #371: The Blackwood Earrings, an interactive noir detective portfolio concept."
  },
  ru: {
    html: "ru",
    title: "UX-кейс - Case File #371 - The Blackwood Earrings",
    description: "UX-кейс проекта Case File #371: The Blackwood Earrings - интерактивного noir-концепта для портфолио."
  },
  pl: {
    html: "pl",
    title: "UX case study - Case File #371 - The Blackwood Earrings",
    description: "UX case study projektu Case File #371: The Blackwood Earrings - interaktywnej noir koncepcji portfolio."
  },
  uk: {
    html: "uk",
    title: "UX-кейс - Case File #371 - The Blackwood Earrings",
    description: "UX-кейс проєкту Case File #371: The Blackwood Earrings - інтерактивної noir-концепції для портфоліо."
  }
};

const translations = {
  ru: {
    "nav.brand":"ДЕЛО #371",
    "nav.study":"UX Case Study",
    "nav.project":"Живой проект",
    
    "hero.label":"ИНТЕРАКТИВНЫЙ UX CASE STUDY",
    "hero.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "hero.subtitle":"Проектирование одностраничного интерактивного детективного опыта, где пользователь изучает улики, находит скрытые подсказки и раскрывает вымышленную кражу драгоценностей через визуальный сторителлинг.",
    "meta.role.label":"Роль",
    "meta.role.value":"UX/UI Designer",
    "meta.type.label":"Тип проекта",
    "meta.type.value":"Интерактивный концепт для портфолио",
    "meta.format.label":"Формат",
    "meta.format.value":"Одностраничный интерактивный опыт",
    "meta.focus.label":"Фокус",
    "meta.focus.value":"Сторителлинг, микроинтеракции, визуальный UI, пользовательский поток",
    "meta.tools.label":"Инструменты",
    "meta.tools.value":"Figma, Photoshop, HTML, CSS, JavaScript",
    "cta.live":"Открыть проект",
    
    "hero.card.confidential":"CONFIDENTIAL",
    "hero.card.solved":"CASE SOLVED",
    "hero.card.label":"UX-ЗАМЕТКИ",
    "hero.card.title":"Blackwood Earrings",
    "hero.card.photo":"превью интерактивного стола",
    "hero.card.note":"Детективная история, рассказанная через объекты, темп и визуальную обратную связь.",
    "overview.title":"ОБЗОР ПРОЕКТА",
    "overview.p1":"The Blackwood Earrings - это одностраничный интерактивный концепт для портфолио, оформленный как стол noir-детектива. Вместо стандартного скролл-лендинга проект приглашает пользователя пройти короткое расследование: открыть папку дела, прочитать отчет, изучить фотографии подозреваемых, найти окурок под чашкой кофе и определить виновного.",
    "overview.p2":"Целью было не создать сложную игру, а спроектировать сфокусированный интерактивный опыт, который показывает визуальный UI, сторителлинг, микроанимации, состояния интерфейса и ясную UX-логику в одной атмосферной сцене.",
    "overview.core.label":"Основная идея",
    "overview.core.value":"Детективная история, рассказанная через предметы на столе.",
    "overview.task.label":"Задача пользователя",
    "overview.task.value":"Найти улику, связать доказательства, раскрыть дело.",
    "overview.outcome.label":"Итог",
    "overview.outcome.value":"Emily, домработница, оказывается виновной.",
    "challenge.title":"ЗАДАЧА",
    "challenge.p1":"Большинство проектов в портфолио пассивны: пользователь скроллит, смотрит экраны и уходит. Этот концепт исследует, как портфолио может стать опытом, а не статичной презентацией. Главная задача - сбалансировать атмосферу и удобство: интерфейс должен был ощущаться загадочным, но не запутанным.",
    "challenge.p2":"Опыт должен был вести пользователя через понятное расследование без длинных инструкций, сложного инвентаря, таймеров или игровых механик, которые отвлекали бы от самого дизайна.",
    "challenge.card1.title":"Сделать взаимодействие естественным",
    "challenge.card1.text":"Пользователь должен понимать, что можно открыть, кликнуть, изучить или сдвинуть, без отдельного обучения.",
    "challenge.card2.title":"Сохранить noir-атмосферу",
    "challenge.card2.text":"Интерфейс должен был быть кинематографичным и взрослым, а не мультяшным или чрезмерно игривым.",
    "challenge.card3.title":"Сохранить короткую историю",
    "challenge.card3.text":"Полный опыт должен проходиться менее чем за три минуты.",
    "challenge.card4.title":"Сделать логику улик читаемой",
    "challenge.card4.text":"Каждая улика должна ясно вести к финальному подозреваемому.",
    "goals.title":"ДИЗАЙН-ЦЕЛИ",
    "goal1.label":"Цель 01",
    "goal1.title":"Пробудить любопытство",
    "goal1.text":"Использовать физические объекты, скрытые подсказки и постепенное раскрытие, чтобы пользователю хотелось исследовать сцену.",
    "goal2.label":"Цель 02",
    "goal2.title":"Минимизировать инструкции",
    "goal2.text":"Заменить длинные объяснения визуальной обратной связью, hover-состояниями, движением объектов и понятными сигналами взаимодействия.",
    "goal3.label":"Цель 03",
    "goal3.title":"Создать кинематографичное настроение",
    "goal3.text":"Использовать теплый свет, старую бумагу, тени, пыль, красные нити и несовершенные текстуры для noir-атмосферы.",
    "goal4.label":"Цель 04",
    "goal4.title":"Упростить поток",
    "goal4.text":"Ограничить опыт одним экраном, одним делом, пятью подозреваемыми, одной скрытой уликой и одним финальным решением.",
    "goal5.label":"Цель 05",
    "goal5.title":"Вознаградить наблюдательность",
    "goal5.text":"Пользователь должен почувствовать себя внимательным, когда найдет окурок и свяжет его с Emily.",
    "goal6.label":"Цель 06",
    "goal6.title":"Показать UI-мастерство",
    "goal6.text":"Использовать hover-эффекты, flip-карточки, lightbox, drag-взаимодействие, печатный эффект и анимированное раскрытие дела.",
    "flow.title":"ПОЛЬЗОВАТЕЛЬСКИЙ ПОТОК",
    "flow.open":"Открыть папку дела",
    "flow.report":"Прочитать отчет",
    "flow.scene":"Изучить фото места преступления",
    "flow.close":"Закрыть файл",
    "flow.review":"Посмотреть полароиды подозреваемых",
    "flow.flip":"Перевернуть карточки",
    "flow.cup":"Сдвинуть чашку кофе",
    "flow.evidence":"Найти окурок",
    "flow.choose":"Выбрать виновного",
    "flow.solved":"Дело раскрыто",
    "flow.note":"Поток построен на постепенном раскрытии. Пользователь получает только ту информацию, которая нужна на текущем этапе. Это удерживает фокус и не перегружает интерфейс.",
    "ia.title":"ИНФОРМАЦИОННАЯ АРХИТЕКТУРА",
    "ia.root":"Сцена на столе",
    "ia.folder":"Папка дела",
    "ia.report":"Отчет о преступлении",
    "ia.earrings":"Фото сережек",
    "ia.scene":"Фото места преступления",
    "ia.suspects":"Фото подозреваемых",
    "ia.hidden":"Скрытая улика",
    "ia.cup":"Чашка кофе",
    "ia.butt":"Окурок",
    "ia.card":"Карточка улики",
    "ia.final":"Финальное решение",
    "ia.wrong":"Обратная связь при ошибке",
    "ia.emilySelected":"Emily выбрана",
    "ia.result":"Результат Case Solved",
    "ia.note":"Информационная архитектура построена вокруг физического сторителлинга. Каждый фрагмент контента появляется как предмет на столе детектива, поэтому интерфейс ощущается как сцена, а не стандартная веб-страница.",
    "name.emily":"Emily",
    "name.james":"James",
    "name.olivia":"Olivia",
    "name.thomas":"Thomas",
    "name.claire":"Claire",
    "interaction.title":"ДИЗАЙН ВЗАИМОДЕЙСТВИЙ",
    "interaction.purpose":"UX-цель:",
    "interaction.block1.label":"Блок 01",
    "interaction.block1.title":"Открытие папки дела",
    "interaction.block1.text":"Закрытая папка дела работает как точка входа в историю. Hover-состояние слегка приподнимает угол папки, а клик открывает файл и визуально приближает пользователя к расследованию. Так появляется ощущение вовлеченности до появления первого документа.",
    "interaction.block1.purpose":"Ввести в историю через физическое действие.",
    "interaction.block2.label":"Блок 02",
    "interaction.block2.title":"Изучение полароидов",
    "interaction.block2.text":"Информация о подозреваемых скрыта на обратной стороне полароидов. Это создает естественный паттерн расследования: пользователь изучает людей по одному, а не получает все факты сразу. У каждой карточки свой поворот, чтобы стол ощущался живым и несовершенным.",
    "interaction.block2.purpose":"Превратить чтение в открытие.",
    "interaction.block3.label":"Блок 03",
    "interaction.block3.title":"Скрытая улика под чашкой",
    "interaction.block3.text":"Чашка кофе сначала выглядит как часть сцены, а не очевидная кнопка. Она становится интерактивной только после просмотра минимум трех подозреваемых. Это не дает найти ключевую улику слишком рано и поддерживает нужный темп расследования.",
    "interaction.block3.purpose":"Управлять темпом без принуждения.",
    "interaction.block4.label":"Блок 04",
    "interaction.block4.title":"Появление улики",
    "interaction.block4.text":"Когда окурок найден, появляется карточка улики с эффектом печатной машинки. Красная помада и ментоловая сигарета напрямую связывают скрытую улику с профилем Emily.",
    "interaction.block4.purpose":"Сделать дедукцию понятной.",
    "interaction.block5.label":"Блок 05",
    "interaction.block5.title":"Финальный выбор подозреваемого",
    "interaction.block5.text":"Финальный выбор делается кликом по фотографии подозреваемого. Ошибочный выбор вызывает легкое дрожание и короткую заметку “Not enough evidence”. Выбор Emily запускает красные нити, штамп CASE SOLVED и финальное объяснение.",
    "interaction.block5.purpose":"Дать мгновенную обратную связь и эмоциональное завершение.",
    "narrative.title":"НАРРАТИВНАЯ ЛОГИКА",
    "narrative.p":"Тайна построена вокруг простой цепочки улик. На месте преступления есть след прожога, но нет сигареты. Позже пользователь находит под чашкой кофе окурок с красной помадой. Факты о подозреваемых помогают исключить всех, кроме Emily.",
    "narrative.james":"Не курит.",
    "narrative.olivia":"Ей 15 лет, поэтому сигаретная улика маловероятна.",
    "narrative.thomas":"Курит, но сам скручивает сигареты. Найденная сигарета тонкая и ментоловая.",
    "narrative.claire":"Не курит и не носит помаду.",
    "narrative.emily":"Иногда курит ментоловые сигареты и всегда носит красную помаду.",
    "narrative.conclusion":"Вывод:",
    "narrative.lines":"След прожога привел к сигарете.<br>Сигарета привела к помаде.<br>Помада привела к Emily.",
    "visual.title":"ВИЗУАЛЬНЫЙ ЯЗЫК",
    "visual.p":"Визуальная система строится вокруг noir-кино и старых материалов детективного дела. Темный деревянный стол становится сценой, старая бумага отвечает за читаемость, приглушенное золото добавляет премиальность, а темно-красный цвет связывает улики. Дизайн избегает ярких цветов, чтобы сохранить серьезное кинематографичное настроение.",
    "visual.color.title":"Цвет",
    "visual.color.text":"Почти черный, темное дерево, состаренный бежевый, грязно-белый, темно-красный, приглушенное золото.",
    "visual.type.title":"Типографика",
    "visual.type.text":"Элегантные serif-заголовки, текст печатной машинки, рукописные подписи полароидов.",
    "visual.texture.title":"Текстура",
    "visual.texture.text":"Бумажное зерно, пыль, кофейные пятна, прожог, потертые края.",
    "visual.light.title":"Свет",
    "visual.light.text":"Мягкое теплое свечение лампы, глубокие тени, тонкая виньетка.",
    "visual.mood.title":"Настроение",
    "visual.mood.text":"Офис частного детектива, поздняя ночь, дорогая кража, тихое напряжение.",
    "components.title":"UI-КОМПОНЕНТЫ",
    "components.p":"Компоненты интерфейса спроектированы как физические объекты, а не стандартные веб-элементы. Кнопки, карточки, модальные окна и состояния обратной связи замаскированы под материалы дела, что сохраняет погружение и функциональную ясность.",
    "component.folder":"Папка дела",
    "component.report":"Документ отчета",
    "component.polaroid":"Полароид",
    "component.reverse":"Оборот полароида",
    "component.evidence":"Карточка улики",
    "component.cup":"Чашка кофе",
    "component.butt":"Окурок",
    "component.string":"Красная нить",
    "component.pins":"Кнопки",
    "component.stamp":"Штамп",
    "component.lightbox":"Фото в lightbox",
    "component.result":"Финальная карточка",
    "micro.title":"МИКРОИНТЕРАКЦИИ",
    "micro.folderHover.label":"Hover папки",
    "micro.folderHover.text":"Легкая подсветка и приподнятый угол.",
    "micro.folderClick.label":"Клик по папке",
    "micro.folderClick.text":"Плавное открытие и небольшое приближение.",
    "micro.document.label":"Появление документа",
    "micro.document.text":"Slide и fade-переход.",
    "micro.polaroidHover.label":"Hover полароида",
    "micro.polaroidHover.text":"Подъем, выравнивание и усиление тени.",
    "micro.polaroidClick.label":"Клик по полароиду",
    "micro.polaroidClick.text":"Flip-анимация с заметками подозреваемого.",
    "micro.cup.label":"Взаимодействие с чашкой",
    "micro.cup.text":"Grab-курсор, легкое движение, drag или click-to-move.",
    "micro.evidence.label":"Появление улики",
    "micro.evidence.text":"Окурок выходит из тени, карточка печатает текст.",
    "micro.wrong.label":"Неверный ответ",
    "micro.wrong.text":"Фото подозреваемого дрожит и показывает “Not enough evidence”.",
    "micro.correct.label":"Верный ответ",
    "micro.correct.text":"Фото Emily подсвечивается, нити соединяют улики, появляется штамп CASE SOLVED.",
    "micro.restart.label":"Restart",
    "micro.restart.text":"Сцена сбрасывается короткой обратной анимацией.",
    "access.title":"ДОСТУПНОСТЬ И УДОБСТВО",
    "access.p":"Несмотря на сильную визуальность, опыт должен оставаться удобным и читаемым. Интерактивным объектам нужны понятные состояния, крупные зоны клика и достаточный контраст между текстом и бумажным фоном.",
    "access.item1":"Читаемые размеры текста",
    "access.item2":"Сильный контраст на документах",
    "access.item3":"Крупные кликабельные зоны",
    "access.item4":"Видимые hover- и focus-состояния",
    "access.item5":"Поддержка клавиатуры для основных действий",
    "access.item6":"Опция reduced motion",
    "access.item7":"Важная информация не передается только цветом",
    "access.item8":"Короткие текстовые блоки",
    "access.item9":"Понятная финальная обратная связь",
    "access.note":"Noir-стиль не должен снижать удобство. Атмосфера поддерживает опыт, но ясность управляет им.",
    "tech.title":"ТЕХНИЧЕСКАЯ СТРУКТУРА",
    "tech.p":"Проект можно собрать как одностраничный front-end опыт на HTML, CSS и JavaScript. Логика основана на простых изменениях состояния, а не на сложных игровых системах.",
    "tech.html":"Структура сцены, документы, полароиды, карточки улик, финальный результат.",
    "tech.css":"Слоистая композиция стола, transforms, тени, текстуры, responsive layout, анимации.",
    "tech.js":"Открытие и закрытие папки, отслеживание просмотренных подозреваемых, разблокировка чашки кофе, показ улики, проверка выбора, restart.",
    "tech.state.title":"Логика состояний",
    "tech.donot.title":"Не строить",
    "tech.donot.1":"инвентарь",
    "tech.donot.2":"таймер",
    "tech.donot.3":"счетчик очков",
    "tech.donot.4":"многостраничную игру",
    "tech.donot.5":"сложную диалоговую систему",
    "decisions.title":"КЛЮЧЕВЫЕ ДИЗАЙН-РЕШЕНИЯ",
    "decision1.label":"Решение 01",
    "decision1.title":"Детективный стол на одном экране",
    "decision1.text":"Весь опыт происходит на одном столе, чтобы сохранить погружение. Вместо переходов между страницами пользователь двигается по истории через взаимодействие с объектами в одном физическом пространстве.",
    "decision2.label":"Решение 02",
    "decision2.title":"Постепенное раскрытие",
    "decision2.text":"Информация появляется только тогда, когда становится релевантной. Это сохраняет чистоту интерфейса и делает каждое открытие намеренным.",
    "decision3.label":"Решение 03",
    "decision3.title":"Отложенная скрытая улика",
    "decision3.text":"Окурок заблокирован, пока пользователь не изучит достаточно подозреваемых. Это защищает структуру истории и не дает решению появиться слишком рано.",
    "decision4.label":"Решение 04",
    "decision4.title":"Физический UI вместо стандартного",
    "decision4.text":"Кнопки и карточки представлены как папки, фото, документы, штампы и заметки с уликами. Интерфейс ощущается частью истории.",
    "decision5.label":"Решение 05",
    "decision5.title":"Ненавязчивое направление",
    "decision5.text":"Дизайн использует hover-обратную связь, тени, движение и изменения курсора вместо прямых инструкций. Пользователь направляется визуально, без разрушения атмосферы.",
    "decision6.label":"Решение 06",
    "decision6.title":"Короткий цикл взаимодействия",
    "decision6.text":"Тайна намеренно короткая. Цель - быстро показать interaction design и UX-мышление, а не создавать полноценную детективную игру.",
    "final.title":"ФИНАЛЬНЫЙ ОПЫТ",
    "final.p":"В конце расследования пользователь выбирает Emily как виновную. Ее фото подсвечивается, красные нити соединяют окурок, место преступления и профиль подозреваемой, а на папке появляется штамп CASE SOLVED.",
    "final.case":"Emily взяла сережки во время уборки спальни.<br>След прожога привел к сигарете.<br>Сигарета привела к помаде.<br>Помада привела к Emily.",
    "final.status":"СЕРЕЖКИ BLACKWOOD БЫЛИ НАЙДЕНЫ.",
    "reflection.title":"РЕФЛЕКСИЯ",
    "reflection.p1":"Этот проект исследует, как interaction design может стать частью сторителлинга. Главная ценность концепта не в самой загадке, а в том, как пользователь раскрывает ее через объекты, движение, визуальную иерархию и контролируемый поток информации.",
    "reflection.p2":"Самой сложной задачей было сохранить атмосферу и не сделать интерфейс запутанным. Каждое взаимодействие должно было ощущаться частью детективной сцены и при этом вести себя как ясный цифровой интерфейс.",
    "reflection.p3":"Если развивать проект дальше, можно добавить несколько концовок, опциональные заметки об уликах, accessibility-тестирование, улучшенную клавиатурную навигацию и адаптивные подсказки для пользователей, которые долго не находят скрытую улику.",
    "footer.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "footer.by":"Интерактивный UX/UI-концепт для портфолио от Yana Ellis.",
    "footer.portfolio":"Назад к портфолио"
  },
  pl: {
    "nav.brand":"AKTA #371",
    "nav.study":"UX Case Study",
    "nav.project":"Projekt live",
    
    "hero.label":"INTERAKTYWNE UX CASE STUDY",
    "hero.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "hero.subtitle":"Projektowanie jednostronicowego interaktywnego doświadczenia detektywistycznego, w którym użytkownik analizuje dowody, odkrywa ukryte wskazówki i rozwiązuje fikcyjną kradzież biżuterii poprzez wizualny storytelling.",
    "meta.role.label":"Rola",
    "meta.role.value":"UX/UI Designer",
    "meta.type.label":"Typ projektu",
    "meta.type.value":"Interaktywna koncepcja portfolio",
    "meta.format.label":"Format",
    "meta.format.value":"Jednostronicowe doświadczenie interaktywne",
    "meta.focus.label":"Fokus",
    "meta.focus.value":"Storytelling, mikrointerakcje, visual UI, user flow",
    "meta.tools.label":"Narzędzia",
    "meta.tools.value":"Figma, Photoshop, HTML, CSS, JavaScript",
    "cta.live":"Zobacz projekt",
    
    "hero.card.confidential":"CONFIDENTIAL",
    "hero.card.solved":"CASE SOLVED",
    "hero.card.label":"NOTATKI UX",
    "hero.card.title":"Blackwood Earrings",
    "hero.card.photo":"podgląd interaktywnego biurka",
    "hero.card.note":"Historia detektywistyczna opowiedziana przez obiekty, tempo i wizualny feedback.",
    "overview.title":"PRZEGLĄD PROJEKTU",
    "overview.p1":"The Blackwood Earrings to jednostronicowa interaktywna koncepcja portfolio zaprojektowana jako biurko detektywa noir. Zamiast prezentować informacje w standardowym układzie scrollowym, projekt zaprasza użytkownika do krótkiego śledztwa: otwarcia teczki, przeczytania raportu, analizy zdjęć podejrzanych, znalezienia niedopałka pod filiżanką kawy i wskazania winnej osoby.",
    "overview.p2":"Celem nie było stworzenie złożonej gry, lecz skupionego doświadczenia interaktywnego, które pokazuje visual UI, storytelling, mikroanimacje, interakcje oparte na stanach i jasną logikę UX w jednej atmosferycznej scenie.",
    "overview.core.label":"Główna idea",
    "overview.core.value":"Historia detektywistyczna opowiedziana przez przedmioty na biurku.",
    "overview.task.label":"Zadanie użytkownika",
    "overview.task.value":"Znajdź wskazówkę, połącz dowody, rozwiąż sprawę.",
    "overview.outcome.label":"Wynik końcowy",
    "overview.outcome.value":"Emily, gospodyni, zostaje ujawniona jako winna.",
    "challenge.title":"WYZWANIE",
    "challenge.p1":"Większość projektów portfolio jest pasywna. Użytkownicy przewijają, oglądają ekrany i wychodzą. Ta koncepcja sprawdza, jak projekt portfolio może stać się doświadczeniem zamiast statycznej prezentacji. Głównym wyzwaniem było zrównoważenie atmosfery i użyteczności: interfejs miał być tajemniczy, ale nigdy mylący.",
    "challenge.p2":"Doświadczenie musiało prowadzić użytkownika przez czytelne śledztwo bez długich instrukcji, złożonego ekwipunku, timerów czy mechanik gry, które odciągałyby uwagę od samego designu.",
    "challenge.card1.title":"Sprawić, by interakcje były naturalne",
    "challenge.card1.text":"Użytkownik powinien rozumieć, co można kliknąć, otworzyć, zbadać lub przesunąć, bez potrzeby tutorialu.",
    "challenge.card2.title":"Zachować atmosferę noir",
    "challenge.card2.text":"Interfejs miał być filmowy i dojrzały, nie kreskówkowy ani przesadnie zabawowy.",
    "challenge.card3.title":"Utrzymać krótką historię",
    "challenge.card3.text":"Całe doświadczenie powinno być możliwe do ukończenia w mniej niż trzy minuty.",
    "challenge.card4.title":"Uczytelnić logikę dowodów",
    "challenge.card4.text":"Każda wskazówka musiała jasno prowadzić do finałowego podejrzanego.",
    "goals.title":"CELE PROJEKTOWE",
    "goal1.label":"Cel 01",
    "goal1.title":"Wzbudzić ciekawość",
    "goal1.text":"Wykorzystać fizyczne obiekty, ukryte wskazówki i stopniowe odkrywanie, aby zachęcić użytkownika do eksploracji sceny.",
    "goal2.label":"Cel 02",
    "goal2.title":"Ograniczyć instrukcje",
    "goal2.text":"Zastąpić długie wyjaśnienia feedbackiem wizualnym, stanami hover, ruchem obiektów i czytelnymi sygnałami interakcji.",
    "goal3.label":"Cel 03",
    "goal3.title":"Zbudować filmowy nastrój",
    "goal3.text":"Użyć ciepłego światła, starego papieru, cieni, kurzu, czerwonych nici i niedoskonałych tekstur, aby stworzyć atmosferę noir.",
    "goal4.label":"Cel 04",
    "goal4.title":"Uprościć flow",
    "goal4.text":"Ograniczyć doświadczenie do jednego ekranu, jednej sprawy, pięciu podejrzanych, jednej ukrytej wskazówki i jednej decyzji końcowej.",
    "goal5.label":"Cel 05",
    "goal5.title":"Nagrodzić spostrzegawczość",
    "goal5.text":"Użytkownik powinien poczuć satysfakcję po znalezieniu niedopałka i połączeniu go z Emily.",
    "goal6.label":"Cel 06",
    "goal6.title":"Pokazać jakość UI",
    "goal6.text":"Wykorzystać hover efekty, flip cards, lightbox, drag interaction, typing effects i animowany feedback rozwiązania sprawy.",
    "flow.title":"USER FLOW",
    "flow.open":"Otwórz teczkę sprawy",
    "flow.report":"Przeczytaj raport",
    "flow.scene":"Zbadaj zdjęcie miejsca zdarzenia",
    "flow.close":"Zamknij plik",
    "flow.review":"Przejrzyj polaroidy podejrzanych",
    "flow.flip":"Odwróć karty podejrzanych",
    "flow.cup":"Przesuń filiżankę kawy",
    "flow.evidence":"Odkryj niedopałek",
    "flow.choose":"Wybierz winnego",
    "flow.solved":"Sprawa rozwiązana",
    "flow.note":"Flow wykorzystuje progressive disclosure. Użytkownik otrzymuje tylko te informacje, które są potrzebne na danym etapie. Dzięki temu doświadczenie pozostaje skupione i nie przeciąża interfejsu.",
    "ia.title":"ARCHITEKTURA INFORMACJI",
    "ia.root":"Scena na biurku",
    "ia.folder":"Teczka sprawy",
    "ia.report":"Raport o przestępstwie",
    "ia.earrings":"Zdjęcie kolczyków",
    "ia.scene":"Zdjęcie miejsca zbrodni",
    "ia.suspects":"Zdjęcia podejrzanych",
    "ia.hidden":"Ukryty dowód",
    "ia.cup":"Filiżanka kawy",
    "ia.butt":"Niedopałek",
    "ia.card":"Karta dowodu",
    "ia.final":"Decyzja finałowa",
    "ia.wrong":"Feedback po błędnym wyborze",
    "ia.emilySelected":"Wybrano Emily",
    "ia.result":"Wynik Case Solved",
    "ia.note":"Architektura informacji została oparta na fizycznym storytellingu. Każdy fragment treści pojawia się jako przedmiot na biurku detektywa, przez co interfejs przypomina scenę, a nie standardowy layout strony.",
    "name.emily":"Emily",
    "name.james":"James",
    "name.olivia":"Olivia",
    "name.thomas":"Thomas",
    "name.claire":"Claire",
    "interaction.title":"PROJEKT INTERAKCJI",
    "interaction.purpose":"Cel UX:",
    "interaction.block1.label":"Blok 01",
    "interaction.block1.title":"Otwarcie teczki sprawy",
    "interaction.block1.text":"Zamknięta teczka działa jako punkt wejścia do historii. Stan hover subtelnie unosi róg folderu, a kliknięcie otwiera akta i przybliża użytkownika do śledztwa. To buduje poczucie zaangażowania przed pojawieniem się pierwszego dokumentu.",
    "interaction.block1.purpose":"Wprowadzić historię przez fizyczne działanie.",
    "interaction.block2.label":"Blok 02",
    "interaction.block2.title":"Inspekcja polaroidów",
    "interaction.block2.text":"Informacje o podejrzanych są ukryte na odwrocie polaroidów. Tworzy to naturalny schemat śledztwa: użytkownik bada każdą osobę po kolei, zamiast otrzymywać wszystkie fakty naraz. Każda karta ma własną rotację, aby biurko było mniej idealne i bardziej realistyczne.",
    "interaction.block2.purpose":"Zamienić czytanie w odkrywanie.",
    "interaction.block3.label":"Blok 03",
    "interaction.block3.title":"Ukryty dowód pod filiżanką",
    "interaction.block3.text":"Filiżanka kawy jest najpierw częścią sceny, a nie oczywistym przyciskiem. Staje się interaktywna dopiero po obejrzeniu co najmniej trzech podejrzanych. To zapobiega zbyt wczesnemu odkryciu kluczowego dowodu i wspiera zamierzone tempo śledztwa.",
    "interaction.block3.purpose":"Kontrolować tempo bez wymuszania.",
    "interaction.block4.label":"Blok 04",
    "interaction.block4.title":"Ujawnienie dowodu",
    "interaction.block4.text":"Po odkryciu niedopałka pojawia się karta dowodu z animacją maszyny do pisania. Czerwona szminka i miętowy papieros bezpośrednio łączą wskazówkę z profilem Emily.",
    "interaction.block4.purpose":"Uczynić dedukcję zrozumiałą.",
    "interaction.block5.label":"Blok 05",
    "interaction.block5.title":"Finałowy wybór podejrzanego",
    "interaction.block5.text":"Finałowy wybór odbywa się przez kliknięcie zdjęcia podejrzanego. Błędne wybory wywołują delikatne drżenie i notatkę “Not enough evidence”. Wybranie Emily uruchamia czerwone nici, stempel CASE SOLVED i końcowe wyjaśnienie.",
    "interaction.block5.purpose":"Dać natychmiastowy feedback i emocjonalne domknięcie.",
    "narrative.title":"LOGIKA NARRACJI",
    "narrative.p":"Zagadka została oparta na prostym łańcuchu wskazówek. Miejsce zdarzenia zaczyna się od śladu przypalenia, ale bez papierosa. Później użytkownik znajduje pod filiżanką niedopałek z czerwoną szminką. Fakty o podejrzanych pomagają wykluczyć wszystkich poza Emily.",
    "narrative.james":"Nie pali.",
    "narrative.olivia":"Ma 15 lat, więc wskazówka z papierosem jest mało prawdopodobna.",
    "narrative.thomas":"Pali, ale sam skręca papierosy. Znaleziony papieros jest cienki i miętowy.",
    "narrative.claire":"Nie pali i nie nosi szminki.",
    "narrative.emily":"Czasami pali miętowe papierosy i zawsze nosi czerwoną szminkę.",
    "narrative.conclusion":"Wniosek:",
    "narrative.lines":"Ślad przypalenia doprowadził do papierosa.<br>Papieros doprowadził do szminki.<br>Szminka doprowadziła do Emily.",
    "visual.title":"JĘZYK WIZUALNY",
    "visual.p":"System wizualny opiera się na kinie noir i starych materiałach detektywistycznych. Ciemne drewniane biurko jest główną sceną, postarzały papier zapewnia czytelność, przygaszone złoto dodaje jakości premium, a ciemna czerwień łączy dowody. Projekt unika jasnych kolorów, aby zachować poważny, filmowy nastrój.",
    "visual.color.title":"Kolor",
    "visual.color.text":"Prawie czarny, ciemne drewno, stary beż, złamana biel, ciemna czerwień, przygaszone złoto.",
    "visual.type.title":"Typografia",
    "visual.type.text":"Eleganckie nagłówki serif, tekst jak z maszyny do pisania, odręczne podpisy polaroidów.",
    "visual.texture.title":"Tekstura",
    "visual.texture.text":"Ziarnistość papieru, kurz, plamy po kawie, przypalenie, zużyte krawędzie.",
    "visual.light.title":"Światło",
    "visual.light.text":"Miękkie ciepłe światło lampy, mocne cienie, subtelna winieta.",
    "visual.mood.title":"Nastrój",
    "visual.mood.text":"Biuro prywatnego detektywa, późna noc, kosztowna kradzież, ciche napięcie.",
    "components.title":"KOMPONENTY UI",
    "components.p":"Komponenty interfejsu zaprojektowano jako fizyczne obiekty, a nie standardowe elementy webowe. Przyciski, karty, modale i stany feedbacku są ukryte w materiałach sprawy, dzięki czemu doświadczenie pozostaje immersyjne i funkcjonalnie czytelne.",
    "component.folder":"Teczka sprawy",
    "component.report":"Dokument raportu",
    "component.polaroid":"Karta polaroid",
    "component.reverse":"Odwrotna strona polaroidu",
    "component.evidence":"Karta dowodu",
    "component.cup":"Filiżanka kawy",
    "component.butt":"Niedopałek",
    "component.string":"Czerwona nić",
    "component.pins":"Pinezki",
    "component.stamp":"Stempel",
    "component.lightbox":"Zdjęcie lightbox",
    "component.result":"Karta finałowa",
    "micro.title":"MIKROINTERAKCJE",
    "micro.folderHover.label":"Hover folderu",
    "micro.folderHover.text":"Subtelna poświata i uniesiony róg.",
    "micro.folderClick.label":"Kliknięcie folderu",
    "micro.folderClick.text":"Płynne otwarcie i lekkie przybliżenie.",
    "micro.document.label":"Ujawnienie dokumentu",
    "micro.document.text":"Przejście slide i fade.",
    "micro.polaroidHover.label":"Hover polaroidu",
    "micro.polaroidHover.text":"Uniesienie, wyprostowanie i mocniejszy cień.",
    "micro.polaroidClick.label":"Kliknięcie polaroidu",
    "micro.polaroidClick.text":"Animacja flip pokazująca notatki podejrzanego.",
    "micro.cup.label":"Interakcja z kawą",
    "micro.cup.text":"Kursor grab, delikatny ruch, drag lub click-to-move.",
    "micro.evidence.label":"Ujawnienie dowodu",
    "micro.evidence.text":"Niedopałek wychodzi z cienia, karta dowodu wpisuje tekst.",
    "micro.wrong.label":"Błędna odpowiedź",
    "micro.wrong.text":"Zdjęcie podejrzanego drży i wyświetla “Not enough evidence”.",
    "micro.correct.label":"Poprawna odpowiedź",
    "micro.correct.text":"Zdjęcie Emily się podświetla, czerwone nici łączą dowody, pojawia się stempel CASE SOLVED.",
    "micro.restart.label":"Restart",
    "micro.restart.text":"Scena resetuje się krótką animacją odwrotną.",
    "access.title":"DOSTĘPNOŚĆ I UŻYTECZNOŚĆ",
    "access.p":"Mimo że projekt jest bardzo wizualny, doświadczenie musi pozostać użyteczne i czytelne. Obiekty interaktywne potrzebują jasnych stanów feedbacku, dużych obszarów kliknięcia i odpowiedniego kontrastu między tekstem a papierowym tłem.",
    "access.item1":"Czytelne rozmiary tekstu",
    "access.item2":"Silny kontrast na dokumentach",
    "access.item3":"Duże cele kliknięcia",
    "access.item4":"Widoczne stany hover i focus",
    "access.item5":"Obsługa klawiatury dla głównych akcji",
    "access.item6":"Opcja reduced motion",
    "access.item7":"Kluczowe informacje nie są ukryte tylko w kolorze",
    "access.item8":"Krótkie bloki tekstu",
    "access.item9":"Czytelny feedback finałowy",
    "access.note":"Styl noir nigdy nie powinien pogarszać użyteczności. Atmosfera wspiera doświadczenie, ale to klarowność nim kieruje.",
    "tech.title":"STRUKTURA TECHNICZNA",
    "tech.p":"Projekt można zbudować jako jednostronicowe doświadczenie front-endowe z użyciem HTML, CSS i JavaScript. Logika opiera się na prostych zmianach stanu, a nie na złożonych systemach gry.",
    "tech.html":"Struktura sceny, dokumenty, polaroidy, karty dowodów, finałowy wynik.",
    "tech.css":"Warstwowa kompozycja biurka, transformacje, cienie, tekstury, responsywny layout, animacje.",
    "tech.js":"Otwieranie i zamykanie teczki, śledzenie obejrzanych podejrzanych, aktywowanie filiżanki, ujawnianie dowodu, walidacja wyboru, restart sprawy.",
    "tech.state.title":"Logika stanów",
    "tech.donot.title":"Nie budować",
    "tech.donot.1":"systemu ekwipunku",
    "tech.donot.2":"timera",
    "tech.donot.3":"licznika punktów",
    "tech.donot.4":"wielostronicowej gry",
    "tech.donot.5":"złożonego systemu dialogów",
    "decisions.title":"KLUCZOWE DECYZJE PROJEKTOWE",
    "decision1.label":"Decyzja 01",
    "decision1.title":"Jednoekranowe biurko detektywa",
    "decision1.text":"Całe doświadczenie odbywa się na jednym biurku, aby zachować immersję. Zamiast przechodzić między stronami, użytkownik porusza się przez historię, wchodząc w interakcję z obiektami w tej samej fizycznej przestrzeni.",
    "decision2.label":"Decyzja 02",
    "decision2.title":"Progressive disclosure",
    "decision2.text":"Informacje pojawiają się tylko wtedy, gdy stają się istotne. Dzięki temu interfejs pozostaje czysty, a każde odkrycie wydaje się celowe.",
    "decision3.label":"Decyzja 03",
    "decision3.title":"Opóźniona ukryta wskazówka",
    "decision3.text":"Niedopałek jest zablokowany, dopóki użytkownik nie obejrzy wystarczającej liczby podejrzanych. Chroni to strukturę narracji i zapobiega zbyt wczesnemu ujawnieniu rozwiązania.",
    "decision4.label":"Decyzja 04",
    "decision4.title":"Fizyczny UI zamiast standardowego",
    "decision4.text":"Przyciski i karty są przedstawione jako teczki, zdjęcia, dokumenty, stemple i notatki dowodowe. Dzięki temu interfejs wydaje się częścią historii.",
    "decision5.label":"Decyzja 05",
    "decision5.title":"Subtelne prowadzenie",
    "decision5.text":"Projekt używa feedbacku hover, cieni, ruchu i zmian kursora zamiast bezpośrednich instrukcji. Użytkownik jest prowadzony wizualnie bez niszczenia atmosfery.",
    "decision6.label":"Decyzja 06",
    "decision6.title":"Krótka pętla interakcji",
    "decision6.text":"Zagadka jest celowo krótka. Celem jest szybkie pokazanie interaction design i myślenia UX, a nie stworzenie pełnej gry detektywistycznej.",
    "final.title":"DOŚWIADCZENIE FINAŁOWE",
    "final.p":"Na końcu śledztwa użytkownik wybiera Emily jako winną. Jej zdjęcie zostaje podświetlone, czerwone nici łączą niedopałek, miejsce zdarzenia i profil podejrzanej, a na teczce pojawia się stempel CASE SOLVED.",
    "final.case":"Emily zabrała kolczyki podczas sprzątania sypialni.<br>Ślad przypalenia doprowadził do papierosa.<br>Papieros doprowadził do szminki.<br>Szminka doprowadziła do Emily.",
    "final.status":"KOLCZYKI BLACKWOOD ZOSTAŁY ODZYSKANE.",
    "reflection.title":"REFLEKSJA",
    "reflection.p1":"Ten projekt bada, jak interaction design może stać się częścią storytellingu. Największą wartością koncepcji nie jest sama tajemnica, ale sposób, w jaki użytkownik odkrywa ją poprzez obiekty, ruch, hierarchię wizualną i kontrolowany przepływ informacji.",
    "reflection.p2":"Największym wyzwaniem było utrzymanie atmosfery bez czynienia interfejsu niejasnym. Każda interakcja musiała wyglądać jak część sceny detektywistycznej, a jednocześnie zachowywać się jak czytelny interfejs cyfrowy.",
    "reflection.p3":"W dalszym rozwoju projekt mógłby zawierać wiele zakończeń, opcjonalne notatki o wskazówkach, testy dostępności, lepszą nawigację klawiaturą i adaptacyjne podpowiedzi dla użytkowników, którzy długo nie znajdują ukrytego dowodu.",
    "footer.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "footer.by":"Interaktywna koncepcja UX/UI portfolio autorstwa Yana Ellis.",
    "footer.portfolio":"Powrót do portfolio"
  },
  uk: {
    "nav.brand":"СПРАВА #371",
    "nav.study":"UX Case Study",
    "nav.project":"Живий проєкт",
    
    "hero.label":"ІНТЕРАКТИВНИЙ UX CASE STUDY",
    "hero.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "hero.subtitle":"Проєктування односторінкового інтерактивного детективного досвіду, де користувач вивчає докази, знаходить приховані підказки й розкриває вигадану крадіжку коштовностей через візуальний сторітелінг.",
    "meta.role.label":"Роль",
    "meta.role.value":"UX/UI Designer",
    "meta.type.label":"Тип проєкту",
    "meta.type.value":"Інтерактивна концепція для портфоліо",
    "meta.format.label":"Формат",
    "meta.format.value":"Односторінковий інтерактивний досвід",
    "meta.focus.label":"Фокус",
    "meta.focus.value":"Сторітелінг, мікроінтеракції, візуальний UI, користувацький потік",
    "meta.tools.label":"Інструменти",
    "meta.tools.value":"Figma, Photoshop, HTML, CSS, JavaScript",
    "cta.live":"Переглянути проєкт",
    
    "hero.card.confidential":"CONFIDENTIAL",
    "hero.card.solved":"CASE SOLVED",
    "hero.card.label":"UX-НОТАТКИ",
    "hero.card.title":"Blackwood Earrings",
    "hero.card.photo":"превʼю інтерактивного столу",
    "hero.card.note":"Детективна історія, розказана через обʼєкти, темп і візуальний фідбек.",
    "overview.title":"ОГЛЯД ПРОЄКТУ",
    "overview.p1":"The Blackwood Earrings - це односторінкова інтерактивна концепція для портфоліо, оформлена як стіл noir-детектива. Замість стандартного scroll-based layout проєкт запрошує користувача пройти коротке розслідування: відкрити папку справи, прочитати звіт, оглянути фото підозрюваних, знайти недопалок під чашкою кави та визначити винну.",
    "overview.p2":"Мета полягала не у створенні складної гри, а в дизайні сфокусованого інтерактивного досвіду, який демонструє visual UI, сторітелінг, мікроанімації, взаємодії на основі станів і чітку UX-логіку в одній атмосферній сцені.",
    "overview.core.label":"Основна ідея",
    "overview.core.value":"Детективна історія, розказана через предмети на столі.",
    "overview.task.label":"Завдання користувача",
    "overview.task.value":"Знайти підказку, повʼязати докази, розкрити справу.",
    "overview.outcome.label":"Фінальний результат",
    "overview.outcome.value":"Emily, домогосподарка, виявляється винною.",
    "challenge.title":"ВИКЛИК",
    "challenge.p1":"Більшість портфоліо-проєктів пасивні. Користувачі скролять, дивляться екрани й ідуть. Ця концепція досліджує, як портфоліо може стати досвідом замість статичної презентації. Головним викликом було збалансувати атмосферу й зручність: інтерфейс мав бути загадковим, але не заплутаним.",
    "challenge.p2":"Досвід мав вести користувача через зрозуміле розслідування без довгих інструкцій, складного інвентарю, таймерів або ігрових механік, які могли б відволікати від дизайну.",
    "challenge.card1.title":"Зробити взаємодію природною",
    "challenge.card1.text":"Користувач має розуміти, що можна клікнути, відкрити, оглянути або пересунути, без окремого туторіалу.",
    "challenge.card2.title":"Зберегти noir-атмосферу",
    "challenge.card2.text":"Інтерфейс мав відчуватися кінематографічним і дорослим, не мультяшним і не надто грайливим.",
    "challenge.card3.title":"Залишити історію короткою",
    "challenge.card3.text":"Повний досвід має проходитися менш ніж за три хвилини.",
    "challenge.card4.title":"Зробити логіку доказів читабельною",
    "challenge.card4.text":"Кожна підказка мала чітко вести до фінальної підозрюваної.",
    "goals.title":"ДИЗАЙН-ЦІЛІ",
    "goal1.label":"Ціль 01",
    "goal1.title":"Заохотити цікавість",
    "goal1.text":"Використати фізичні обʼєкти, приховані підказки й поступове розкриття, щоб користувач хотів досліджувати сцену.",
    "goal2.label":"Ціль 02",
    "goal2.title":"Мінімізувати інструкції",
    "goal2.text":"Замінити довгі пояснення візуальним фідбеком, hover-станами, рухом обʼєктів і зрозумілими сигналами взаємодії.",
    "goal3.label":"Ціль 03",
    "goal3.title":"Створити кінематографічний настрій",
    "goal3.text":"Використати тепле світло, старий папір, тіні, пил, червоні нитки й недосконалі текстури для noir-атмосфери.",
    "goal4.label":"Ціль 04",
    "goal4.title":"Зробити flow простим",
    "goal4.text":"Обмежити досвід одним екраном, однією справою, пʼятьма підозрюваними, однією прихованою підказкою й одним фінальним рішенням.",
    "goal5.label":"Ціль 05",
    "goal5.title":"Винагородити спостережливість",
    "goal5.text":"Користувач має відчути себе кмітливим, коли знайде недопалок і повʼяже його з Emily.",
    "goal6.label":"Ціль 06",
    "goal6.title":"Показати UI-майстерність",
    "goal6.text":"Використати hover-ефекти, flip-картки, lightbox, drag-взаємодію, typing effects і анімований фідбек розкритої справи.",
    "flow.title":"КОРИСТУВАЦЬКИЙ ПОТІК",
    "flow.open":"Відкрити папку справи",
    "flow.report":"Прочитати звіт",
    "flow.scene":"Оглянути фото місця злочину",
    "flow.close":"Закрити файл",
    "flow.review":"Переглянути полароїди підозрюваних",
    "flow.flip":"Перевернути картки",
    "flow.cup":"Посунути чашку кави",
    "flow.evidence":"Знайти недопалок",
    "flow.choose":"Обрати винну",
    "flow.solved":"Справу розкрито",
    "flow.note":"Потік використовує progressive disclosure. Користувач отримує лише ту інформацію, яка потрібна на кожному етапі. Це утримує фокус і не перевантажує інтерфейс.",
    "ia.title":"ІНФОРМАЦІЙНА АРХІТЕКТУРА",
    "ia.root":"Сцена на столі",
    "ia.folder":"Папка справи",
    "ia.report":"Звіт про злочин",
    "ia.earrings":"Фото сережок",
    "ia.scene":"Фото місця злочину",
    "ia.suspects":"Фото підозрюваних",
    "ia.hidden":"Прихований доказ",
    "ia.cup":"Чашка кави",
    "ia.butt":"Недопалок",
    "ia.card":"Картка доказу",
    "ia.final":"Фінальне рішення",
    "ia.wrong":"Фідбек помилкового вибору",
    "ia.emilySelected":"Emily обрана",
    "ia.result":"Результат Case Solved",
    "ia.note":"Інформаційна архітектура побудована навколо фізичного сторітелінгу. Кожен фрагмент контенту зʼявляється як обʼєкт на столі детектива, тому інтерфейс відчувається як сцена, а не стандартна вебсторінка.",
    "name.emily":"Emily",
    "name.james":"James",
    "name.olivia":"Olivia",
    "name.thomas":"Thomas",
    "name.claire":"Claire",
    "interaction.title":"ДИЗАЙН ВЗАЄМОДІЙ",
    "interaction.purpose":"UX-мета:",
    "interaction.block1.label":"Блок 01",
    "interaction.block1.title":"Відкриття папки справи",
    "interaction.block1.text":"Закрита папка справи є точкою входу в історію. Hover-стан ледь піднімає кут папки, а клік відкриває файл і наближає користувача до розслідування. Це створює відчуття залучення ще до появи першого документа.",
    "interaction.block1.purpose":"Ввести історію через фізичну дію.",
    "interaction.block2.label":"Блок 02",
    "interaction.block2.title":"Огляд полароїдів",
    "interaction.block2.text":"Інформація про підозрюваних прихована на звороті кожного полароїда. Це створює природний патерн розслідування: користувач оглядає кожну людину замість того, щоб одразу отримати всі факти. Кожна картка має власний нахил, щоб стіл відчувався недосконалим і реалістичним.",
    "interaction.block2.purpose":"Перетворити читання на відкриття.",
    "interaction.block3.label":"Блок 03",
    "interaction.block3.title":"Прихований доказ під чашкою",
    "interaction.block3.text":"Чашка кави спочатку задумана як частина сцени, а не очевидна кнопка. Вона стає інтерактивною лише після того, як користувач оглянув щонайменше трьох підозрюваних. Це не дозволяє знайти ключовий доказ занадто рано й підтримує задуманий темп розслідування.",
    "interaction.block3.purpose":"Контролювати темп без примусу.",
    "interaction.block4.label":"Блок 04",
    "interaction.block4.title":"Поява доказу",
    "interaction.block4.text":"Коли недопалок знайдено, зʼявляється картка доказу з анімацією друкарської машинки. Червона помада й ментолова сигарета напряму повʼязують приховану підказку з профілем Emily.",
    "interaction.block4.purpose":"Зробити дедукцію зрозумілою.",
    "interaction.block5.label":"Блок 05",
    "interaction.block5.title":"Фінальний вибір підозрюваної",
    "interaction.block5.text":"Фінальний вибір робиться кліком по фото підозрюваного. Неправильний вибір викликає легке тремтіння й коротку нотатку “Not enough evidence”. Вибір Emily запускає червоні нитки, штамп CASE SOLVED і фінальне пояснення.",
    "interaction.block5.purpose":"Дати миттєвий фідбек і емоційне завершення.",
    "narrative.title":"НАРАТИВНА ЛОГІКА",
    "narrative.p":"Таємниця побудована навколо простого ланцюжка підказок. На місці злочину є слід опіку, але немає сигарети. Пізніше користувач знаходить під чашкою кави недопалок із червоною помадою. Факти про підозрюваних допомагають виключити всіх, крім Emily.",
    "narrative.james":"Не курить.",
    "narrative.olivia":"Їй 15 років, тому сигаретна підказка малоймовірна.",
    "narrative.thomas":"Курить, але сам скручує сигарети. Знайдена сигарета тонка й ментолова.",
    "narrative.claire":"Не курить і не носить помаду.",
    "narrative.emily":"Іноді курить ментолові сигарети й завжди носить червону помаду.",
    "narrative.conclusion":"Висновок:",
    "narrative.lines":"Слід опіку привів до сигарети.<br>Сигарета привела до помади.<br>Помада привела до Emily.",
    "visual.title":"ВІЗУАЛЬНА МОВА",
    "visual.p":"Візуальна система побудована навколо noir-кіно та старих матеріалів детективної справи. Темний деревʼяний стіл є головною сценою, зістарений папір забезпечує читабельність, приглушене золото додає преміальності, а темно-червоний колір повʼязує докази. Дизайн уникає яскравих кольорів, щоб зберегти серйозний кінематографічний настрій.",
    "visual.color.title":"Колір",
    "visual.color.text":"Майже чорний, темне дерево, зістарений бежевий, брудно-білий, темно-червоний, приглушене золото.",
    "visual.type.title":"Типографіка",
    "visual.type.text":"Елегантні serif-заголовки, текст друкарської машинки, рукописні підписи полароїдів.",
    "visual.texture.title":"Текстура",
    "visual.texture.text":"Паперове зерно, пил, кавові плями, опік, потерті краї.",
    "visual.light.title":"Світло",
    "visual.light.text":"Мʼяке тепле світло лампи, глибокі тіні, тонка віньєтка.",
    "visual.mood.title":"Настрій",
    "visual.mood.text":"Офіс приватного детектива, пізня ніч, дорога крадіжка, тиха напруга.",
    "components.title":"UI-КОМПОНЕНТИ",
    "components.p":"Компоненти інтерфейсу спроєктовані як фізичні обʼєкти, а не стандартні веб-елементи. Кнопки, картки, модальні вікна й стани фідбеку замасковані під матеріали справи, що зберігає занурення і функціональну ясність.",
    "component.folder":"Папка справи",
    "component.report":"Документ звіту",
    "component.polaroid":"Полароїд",
    "component.reverse":"Зворот полароїда",
    "component.evidence":"Картка доказу",
    "component.cup":"Чашка кави",
    "component.butt":"Недопалок",
    "component.string":"Червона нитка",
    "component.pins":"Кнопки",
    "component.stamp":"Штамп",
    "component.lightbox":"Фото lightbox",
    "component.result":"Фінальна картка",
    "micro.title":"МІКРОІНТЕРАКЦІЇ",
    "micro.folderHover.label":"Hover папки",
    "micro.folderHover.text":"Легка підсвітка й піднятий кут.",
    "micro.folderClick.label":"Клік по папці",
    "micro.folderClick.text":"Плавне відкриття й невелике наближення.",
    "micro.document.label":"Поява документа",
    "micro.document.text":"Slide і fade-перехід.",
    "micro.polaroidHover.label":"Hover полароїда",
    "micro.polaroidHover.text":"Підняття, вирівнювання й посилення тіні.",
    "micro.polaroidClick.label":"Клік по полароїду",
    "micro.polaroidClick.text":"Flip-анімація з нотатками підозрюваного.",
    "micro.cup.label":"Взаємодія з чашкою",
    "micro.cup.text":"Grab-курсор, легкий рух, drag або click-to-move.",
    "micro.evidence.label":"Поява доказу",
    "micro.evidence.text":"Недопалок зʼявляється з тіні, картка доказу друкує текст.",
    "micro.wrong.label":"Неправильна відповідь",
    "micro.wrong.text":"Фото підозрюваного тремтить і показує “Not enough evidence”.",
    "micro.correct.label":"Правильна відповідь",
    "micro.correct.text":"Фото Emily підсвічується, червоні нитки зʼєднують докази, зʼявляється штамп CASE SOLVED.",
    "micro.restart.label":"Restart",
    "micro.restart.text":"Сцена скидається короткою зворотною анімацією.",
    "access.title":"ДОСТУПНІСТЬ І ЗРУЧНІСТЬ",
    "access.p":"Хоча проєкт дуже візуальний, досвід має залишатися зручним і читабельним. Інтерактивним обʼєктам потрібні зрозумілі стани фідбеку, великі області кліку й достатній контраст між текстом і паперовим фоном.",
    "access.item1":"Читабельні розміри тексту",
    "access.item2":"Сильний контраст на документах",
    "access.item3":"Великі клікабельні цілі",
    "access.item4":"Видимі hover- і focus-стани",
    "access.item5":"Підтримка клавіатури для основних дій",
    "access.item6":"Опція reduced motion",
    "access.item7":"Важлива інформація не прихована лише в кольорі",
    "access.item8":"Короткі текстові блоки",
    "access.item9":"Зрозумілий фінальний фідбек",
    "access.note":"Noir-стиль не повинен знижувати зручність. Атмосфера підтримує досвід, але ясність ним керує.",
    "tech.title":"ТЕХНІЧНА СТРУКТУРА",
    "tech.p":"Проєкт можна зібрати як односторінковий front-end досвід на HTML, CSS і JavaScript. Логіка базується на простих змінах стану, а не на складних ігрових системах.",
    "tech.html":"Структура сцени, документи, полароїди, картки доказів, фінальний результат.",
    "tech.css":"Шарова композиція столу, transforms, тіні, текстури, responsive layout, анімації.",
    "tech.js":"Відкриття й закриття папки, відстеження переглянутих підозрюваних, активація чашки кави, показ доказу, перевірка вибору, restart.",
    "tech.state.title":"Логіка станів",
    "tech.donot.title":"Не будувати",
    "tech.donot.1":"систему інвентарю",
    "tech.donot.2":"таймер",
    "tech.donot.3":"лічильник балів",
    "tech.donot.4":"багатосторінкову гру",
    "tech.donot.5":"складну діалогову систему",
    "decisions.title":"КЛЮЧОВІ ДИЗАЙН-РІШЕННЯ",
    "decision1.label":"Рішення 01",
    "decision1.title":"Детективний стіл на одному екрані",
    "decision1.text":"Увесь досвід відбувається на одному столі, щоб зберегти занурення. Замість переходів між сторінками користувач рухається історією через взаємодію з обʼєктами в одному фізичному просторі.",
    "decision2.label":"Рішення 02",
    "decision2.title":"Progressive disclosure",
    "decision2.text":"Інформація зʼявляється лише тоді, коли стає релевантною. Це зберігає чистоту інтерфейсу й робить кожне відкриття навмисним.",
    "decision3.label":"Рішення 03",
    "decision3.title":"Відкладена прихована підказка",
    "decision3.text":"Недопалок заблокований, доки користувач не огляне достатньо підозрюваних. Це захищає структуру історії й не дозволяє рішенню зʼявитися занадто рано.",
    "decision4.label":"Рішення 04",
    "decision4.title":"Фізичний UI замість стандартного",
    "decision4.text":"Кнопки й картки представлені як папки, фото, документи, штампи й нотатки з доказами. Інтерфейс відчувається частиною історії.",
    "decision5.label":"Рішення 05",
    "decision5.title":"Ненавʼязливе спрямування",
    "decision5.text":"Дизайн використовує hover-фідбек, тіні, рух і зміни курсора замість прямих інструкцій. Користувач скеровується візуально, без руйнування атмосфери.",
    "decision6.label":"Рішення 06",
    "decision6.title":"Короткий цикл взаємодії",
    "decision6.text":"Таємниця навмисно коротка. Мета - швидко показати interaction design і UX-мислення, а не створити повноцінну детективну гру.",
    "final.title":"ФІНАЛЬНИЙ ДОСВІД",
    "final.p":"Наприкінці розслідування користувач обирає Emily як винну. Її фото підсвічується, червоні нитки зʼєднують недопалок, місце злочину й профіль підозрюваної, а на папці зʼявляється штамп CASE SOLVED.",
    "final.case":"Emily взяла сережки під час прибирання спальні.<br>Слід опіку привів до сигарети.<br>Сигарета привела до помади.<br>Помада привела до Emily.",
    "final.status":"СЕРЕЖКИ BLACKWOOD БУЛО ЗНАЙДЕНО.",
    "reflection.title":"РЕФЛЕКСІЯ",
    "reflection.p1":"Цей проєкт досліджує, як interaction design може стати частиною сторітелінгу. Головна цінність концепції не в самій загадці, а в тому, як користувач розкриває її через обʼєкти, рух, візуальну ієрархію та контрольований потік інформації.",
    "reflection.p2":"Найбільшим викликом було зберегти атмосферу й не зробити інтерфейс заплутаним. Кожна взаємодія мала відчуватися частиною детективної сцени й водночас поводитися як ясний цифровий інтерфейс.",
    "reflection.p3":"Якщо розвивати проєкт далі, можна додати кілька кінцівок, опційні нотатки про підказки, accessibility testing, покращену клавіатурну навігацію та адаптивні підказки для користувачів, які довго не знаходять прихований доказ.",
    "footer.title":"CASE FILE #371<br>THE BLACKWOOD EARRINGS",
    "footer.by":"Інтерактивна UX/UI-концепція для портфоліо від Yana Ellis.",
    "footer.portfolio":"Назад до портфоліо"
  }
};

function safeStorageGet(key) {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

function safeStorageSet(key, value) {
  try {
    localStorage.setItem(key, value);
  } catch {
    // Private browsing or file previews may block storage; language switching still works.
  }
}

function applyLanguage(lang) {
  const activeLang = lang === "en" || translations[lang] ? lang : "en";
  const dictionary = translations[activeLang] || {};
  const meta = languageMeta[activeLang] || languageMeta.en;

  document.documentElement.lang = meta.html;
  titleNode.textContent = meta.title;
  descriptionNode.setAttribute("content", meta.description);

  i18nNodes.forEach(node => {
    const key = node.dataset.i18n;
    node.innerHTML = activeLang === "en" ? node.dataset.i18nDefault : dictionary[key] || node.dataset.i18nDefault;
  });

  languageButtons.forEach(button => {
    const isActive = button.dataset.lang === activeLang;
    button.setAttribute("aria-pressed", String(isActive));
  });

  safeStorageSet("blackwood-case-study-language", activeLang);
}

languageButtons.forEach(button => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

const revealItems = [...document.querySelectorAll(".reveal")];
if ("IntersectionObserver" in window && !prefersReducedMotion.matches) {
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      }
    });
  }, {threshold:.15, rootMargin:"0px 0px -8% 0px"});
  revealItems.forEach(item => observer.observe(item));
} else {
  revealItems.forEach(item => item.classList.add("is-visible"));
}

document.addEventListener("pointermove", event => {
  if (prefersReducedMotion.matches) return;
  const x = (event.clientX / innerWidth - .5) * 18;
  const y = (event.clientY / innerHeight - .5) * 12;
  document.documentElement.style.setProperty("--mx", `${x}px`);
  document.documentElement.style.setProperty("--my", `${y}px`);
});

const savedLanguage = safeStorageGet("blackwood-case-study-language");
applyLanguage(savedLanguage && languageMeta[savedLanguage] ? savedLanguage : "en");
